// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Raw = { };

var query = "mutation MyMutation($required: String!)  {\noptionalInputArgs(required: $required, anotherRequired: \"val\")  \n}\n";

function parse(value) {
  return {
          optionalInputArgs: value.optionalInputArgs
        };
}

function serialize(value) {
  return {
          optionalInputArgs: value.optionalInputArgs
        };
}

function serializeVariables(inp) {
  return {
          required: inp.required
        };
}

function makeVariables(required, param) {
  return serializeVariables({
              required: required
            });
}

var definition = /* tuple */[
  parse,
  query,
  serialize
];

var MyQuery = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  definition: definition
};

exports.MyQuery = MyQuery;
/* No side effect */
