// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Caml_option = require("bs-platform/lib/js/caml_option.js");

var Raw = { };

var query = "query ($arg: NonrecursiveInput!)  {\nnonrecursiveInput(arg: $arg)  \n}\n";

function parse(value) {
  return {
          nonrecursiveInput: value.nonrecursiveInput
        };
}

function serialize(value) {
  return {
          nonrecursiveInput: value.nonrecursiveInput
        };
}

function serializeInputObjectEmbeddedInput(inp) {
  var a = inp.field;
  return {
          field: a !== undefined ? a : undefined
        };
}

function serializeInputObjectNonrecursiveInput(inp) {
  var a = inp.nullableArray;
  var tmp;
  if (a !== undefined) {
    var a$1 = a;
    tmp = $$Array.map((function (b) {
            if (b !== undefined) {
              return b;
            }
            
          }), a$1);
  } else {
    tmp = undefined;
  }
  var a$2 = inp.field;
  var a$3 = inp.enum;
  var tmp$1;
  if (a$3 !== undefined) {
    var a$4 = a$3;
    tmp$1 = a$4 !== 225952583 ? (
        a$4 >= 382368628 ? "SECOND" : "FIRST"
      ) : "THIRD";
  } else {
    tmp$1 = undefined;
  }
  var a$5 = inp.embeddedInput;
  var tmp$2;
  if (a$5 !== undefined) {
    var a$6 = a$5;
    tmp$2 = $$Array.map((function (b) {
            if (b !== undefined) {
              return serializeInputObjectEmbeddedInput(Caml_option.valFromOption(b));
            }
            
          }), a$6);
  } else {
    tmp$2 = undefined;
  }
  return {
          nonNullableField: inp.nonNullableField,
          nullableArray: tmp,
          field: a$2 !== undefined ? a$2 : undefined,
          enum: tmp$1,
          embeddedInput: tmp$2
        };
}

function serializeVariables(inp) {
  return {
          arg: serializeInputObjectNonrecursiveInput(inp.arg)
        };
}

function makeVariables(arg, param) {
  return serializeVariables({
              arg: arg
            });
}

function makeInputObjectNonrecursiveInput(nonNullableField, nullableArray, field, $$enum, embeddedInput, param) {
  return {
          nonNullableField: nonNullableField,
          nullableArray: nullableArray,
          field: field,
          enum: $$enum,
          embeddedInput: embeddedInput
        };
}

function makeInputObjectEmbeddedInput(field, param) {
  return {
          field: field
        };
}

var definition = /* tuple */[
  parse,
  query,
  serialize
];

var MyQuery = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  serializeInputObjectNonrecursiveInput: serializeInputObjectNonrecursiveInput,
  serializeInputObjectEmbeddedInput: serializeInputObjectEmbeddedInput,
  makeVariables: makeVariables,
  makeInputObjectNonrecursiveInput: makeInputObjectNonrecursiveInput,
  makeInputObjectEmbeddedInput: makeInputObjectEmbeddedInput,
  definition: definition
};

exports.MyQuery = MyQuery;
/* No side effect */
