// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("bs-platform/lib/js/caml_option.js");

var Raw = { };

function parse(value) {
  var value$1 = value.pokemon;
  var tmp;
  if (value$1 == null) {
    tmp = undefined;
  } else {
    var value$2 = value$1.name;
    var name = !(value$2 == null) ? value$2 : undefined;
    var value$3 = value$1.id;
    tmp = {
      id: value$3,
      name: name
    };
  }
  return {
          pokemon: tmp
        };
}

function serialize(value) {
  var value$1 = value.pokemon;
  var tmp;
  if (value$1 !== undefined) {
    var value$2 = Caml_option.valFromOption(value$1);
    var value$3 = value$2.name;
    var name = value$3 !== undefined ? value$3 : null;
    var value$4 = value$2.id;
    tmp = {
      id: value$4,
      name: name
    };
  } else {
    tmp = null;
  }
  return {
          pokemon: tmp
        };
}

function makeVariables(param) {
  
}

var Z__INTERNAL = {
  graphql_module: 0
};

var MyQuery = {
  Raw: Raw,
  query: "query   {\npokemon(name: \"Pikachu\")  {\nid  \nname  \n}\n\n}\n",
  parse: parse,
  serialize: serialize,
  makeVariables: makeVariables,
  makeDefaultVariables: undefined,
  Z__INTERNAL: Z__INTERNAL
};

exports.MyQuery = MyQuery;
/* No side effect */
