// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var Raw = { };

var query = (require("gql")`
  query   {
    pokemon(name: "Pikachu")  {
      id
      name
    }
  }
`);

function parse(value) {
  var value$1 = value.pokemon;
  var tmp;
  if (value$1 == null) {
    tmp = undefined;
  } else {
    var value$2 = value$1.name;
    tmp = {
      id: value$1.id,
      name: !(value$2 == null) ? value$2 : undefined
    };
  }
  return {
          pokemon: tmp
        };
}

function serialize(value) {
  var value$1 = value.pokemon;
  var pokemon;
  if (value$1 !== undefined) {
    var value$2 = value$1.name;
    var name = value$2 !== undefined ? value$2 : null;
    var value$3 = value$1.id;
    pokemon = {
      id: value$3,
      name: name
    };
  } else {
    pokemon = null;
  }
  return {
          pokemon: pokemon
        };
}

function serializeVariables(param) {
  
}

function makeVariables(param) {
  
}

function makeDefaultVariables(param) {
  
}

var Z__INTERNAL = {
  _graphql_name_52: 0,
  graphql_module: 0
};

var MyQuery = {
  Raw: Raw,
  query: query,
  parse: parse,
  serialize: serialize,
  serializeVariables: serializeVariables,
  makeVariables: makeVariables,
  makeDefaultVariables: makeDefaultVariables,
  Z__INTERNAL: Z__INTERNAL
};

exports.MyQuery = MyQuery;
/* query Not a pure module */
