[@ocaml.ppx.context
  {
    tool_name: "migrate_driver",
    include_dirs: [],
    load_path: [],
    open_modules: [],
    for_package: None,
    debug: false,
    use_threads: false,
    use_vmthreads: false,
    recursive_types: false,
    principal: false,
    transparent_modules: false,
    unboxed_types: false,
    unsafe_string: false,
    cookies: [],
  }
];
module MyQuery = {
  module Raw = {
    type t = {. "argNamedQuery": int};
    type t_variables = {. "query": int};
  };
  /**The GraphQL query string*/
  let query = "query ($query: Int!)  {\nargNamedQuery(query: $query)  \n}\n";
  type t = {. "argNamedQuery": int};
  type t_variables = {. "query": int};
  /**Parse the JSON GraphQL data to ReasonML data types*/
  let parse = (value: Raw.t): t => {
    let argNamedQuery = {
      let value = value##argNamedQuery;
      value;
    };
    {"argNamedQuery": argNamedQuery};
  };
  /**Serialize the ReasonML GraphQL data that was parsed using the parse function back to the original JSON compatible data */
  let serialize = (value: t): Raw.t => {
    let argNamedQuery = {
      let value = value##argNamedQuery;
      value;
    };
    {"argNamedQuery": argNamedQuery};
  };
  let serializeVariables: t_variables => Raw.t_variables =
    inp => {"query": (a => a)(inp##query)};
  let make = (~query, ()) => {
    "query": query,
    "variables": serializeVariables({"query": query}: t_variables),
    "parse": parse,
  }
  and makeVariables = (~query, ()) =>
    serializeVariables({"query": query}: t_variables);
  let makeWithVariables = variables => {
    "query": query,
    "variables": serializeVariables(variables),
    "parse": parse,
  };
  module Z__INTERNAL = {
    type root = t;
    type nonrec graphql_module;
    /****--- GraphQL PPX Module ---**

The contents of this module are automatically generated by `graphql-ppx`.
The following is simply an overview of the most important variables and types that you can access from this module.

```
module MyQuery {
  /**
  The GraphQL query string
  */
  let query: string;

  /**
  This is the main type of the result you will get back.
  You can hover above the identifier key (e.g. query or mutation) to see the fully generated type for your module.
  */
  type t;

  /**
  Parse the JSON GraphQL data to ReasonML data types
  */
  let parse: Raw.t => t;

  /**
  Serialize the ReasonML GraphQL data that was parsed using the parse function back to the original JSON compatible data
  */
  let serialize: t => Raw.t;

  /**
  This is the JSON compatible type of the GraphQL data.
  It should not be necessary to access the types inside for normal use cases.
  */
  module Raw: { type t; };
}
```*/
    let graphql_module: graphql_module = Obj.magic(0);
  };
};
