[@ocaml.ppx.context
  {
    tool_name: "migrate_driver",
    include_dirs: [],
    load_path: [],
    open_modules: [],
    for_package: None,
    debug: false,
    use_threads: false,
    use_vmthreads: false,
    recursive_types: false,
    principal: false,
    transparent_modules: false,
    unboxed_types: false,
    unsafe_string: false,
    cookies: [],
  }
];
module MyQuery = {
  module Raw = {
    type t_simpleSubscription_Dog = {
      __typename: string,
      name: string,
    };
    type t_simpleSubscription_Human = {
      __typename: string,
      name: string,
    };
    type t_simpleSubscription;
    type t = {simpleSubscription: t_simpleSubscription};
    type t_variables = Js.Json.t;
  };
  let query = "subscription   {\nsimpleSubscription  {\n__typename\n...on Dog   {\n__typename  \nname  \n}\n\n...on Human   {\n__typename  \nname  \n}\n\n}\n\n}\n";
  type t_simpleSubscription_Dog = {
    __typename: string,
    name: string,
  };
  type t_simpleSubscription_Human = {
    __typename: string,
    name: string,
  };
  type t_simpleSubscription = [
    | `FutureAddedValue(Js.Json.t)
    | `Dog(t_simpleSubscription_Dog)
    | `Human(t_simpleSubscription_Human)
  ];
  type t = {simpleSubscription: t_simpleSubscription};
  type t_variables = Js.Json.t;
  let parse: Raw.t => t =
    (value) => (
      {
        simpleSubscription: {
          let value = (value: Raw.t).simpleSubscription;
          let typename: string =
            Obj.magic(Js.Dict.unsafeGet(Obj.magic(value), "__typename"));
          (
            switch (typename) {
            | "Dog" =>
              `Dog(
                {
                  let value: Raw.t_simpleSubscription_Dog = Obj.magic(value);
                  (
                    {
                      __typename: {
                        let value =
                          (value: Raw.t_simpleSubscription_Dog).__typename;
                        value;
                      },
                      name: {
                        let value = (value: Raw.t_simpleSubscription_Dog).name;
                        value;
                      },
                    }: t_simpleSubscription_Dog
                  );
                },
              )
            | "Human" =>
              `Human(
                {
                  let value: Raw.t_simpleSubscription_Human = Obj.magic(value);
                  (
                    {
                      __typename: {
                        let value =
                          (value: Raw.t_simpleSubscription_Human).__typename;
                        value;
                      },
                      name: {
                        let value =
                          (value: Raw.t_simpleSubscription_Human).name;
                        value;
                      },
                    }: t_simpleSubscription_Human
                  );
                },
              )
            | _ => `FutureAddedValue(Obj.magic(value): Js.Json.t)
            }: t_simpleSubscription
          );
        },
      }: t
    );
  let serialize: t => Raw.t =
    (value) => (
      {
        let simpleSubscription = {
          let value = (value: t).simpleSubscription;
          switch (value) {
          | `Dog(value) => (
              Obj.magic(
                {
                  let name = {
                    let value = (value: t_simpleSubscription_Dog).name;
                    value;
                  }
                  and __typename = {
                    let value = (value: t_simpleSubscription_Dog).__typename;
                    value;
                  };
                  {__typename: "Dog", name};
                }: Raw.t_simpleSubscription_Dog,
              ): Raw.t_simpleSubscription
            )
          | `Human(value) => (
              Obj.magic(
                {
                  let name = {
                    let value = (value: t_simpleSubscription_Human).name;
                    value;
                  }
                  and __typename = {
                    let value = (value: t_simpleSubscription_Human).__typename;
                    value;
                  };
                  {__typename: "Human", name};
                }: Raw.t_simpleSubscription_Human,
              ): Raw.t_simpleSubscription
            )
          | `FutureAddedValue(value) => (
              Obj.magic(value): Raw.t_simpleSubscription
            )
          };
        };
        {simpleSubscription: simpleSubscription};
      }: Raw.t
    );
  module Z__INTERNAL = {
    type root = t;
    type nonrec graphql_module;
    /****--- GraphQL PPX Module ---**

The contents of this module are automatically generated by `graphql-ppx`.
The following is simply an overview of the most important variables and types that you can access from this module.

```
module MyQuery {
  // This is the stringified representation of your query, which gets sent to the server.
  let query: string;

  // This is the main type of the result you will get back.
  // You can hover above the identifier key (e.g. query or mutation) to see the fully generated type for your module.
  type t;

  // This function turns your raw result from the server into the reason/ocaml representation of that result.
  // Depending on your graphql client library, this process should happen automatically for you.
  let parse: Raw.t => t;

  // This function will prepare your data for sending it back to the server.
  // Depending on your graphql client library, this process should happen automatically for you.
  let serialize: t => Raw.t;

  // The definition tuple is primarily used to interact with client libraries.
  // The types are equivalent to: (parse, query, serialize).
  // Your client library will use these values to provide the properly parsed / serialized data for you.
  let definition: (
    Raw.t => t,
    string,
    t => Raw.t
  );

  // This is the representation of your raw result coming from the server.
  // It should not be necessary to access the types inside for normal use cases.
  module Raw: { type t; };
}
```*/
    let graphql_module: graphql_module = Obj.magic(0);
  };
};
