// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Js_dict from "bs-platform/lib/es6/js_dict.js";
import * as Js_json from "bs-platform/lib/es6/js_json.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function deepMerge(json1, json2) {
  var match = Js_json.decodeObject(json1);
  var match$1 = Js_json.decodeObject(json2);
  if (match === undefined) {
    return json2;
  }
  if (match$1 === undefined) {
    return json2;
  }
  var obj2 = Caml_option.valFromOption(match$1);
  var obj1 = Object.assign({ }, Caml_option.valFromOption(match));
  Object.keys(obj2).forEach((function (key) {
          var match = Js_dict.get(obj1, key);
          var match$1 = obj2[key];
          obj1[key] = match !== undefined ? deepMerge(Caml_option.valFromOption(match), match$1) : match$1;
          
        }));
  return obj1;
}

export {
  deepMerge ,
  
}
/* No side effect */
